# -*- coding: utf-8 -*-
"""remove and replace-background.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U_aQWfRMwL75_W6t3urVvppdhLZ47yZn
"""

!pip install -U pillow

!pip install easygui

!pip install rembg

from rembg import remove

import requests

from PIL import Image

from io import BytesIO
import os

os.makedirs("original" , exist_ok =  True)
os.makedirs("masked" , exist_ok =  True)

img_url = "https://raw.githubusercontent.com/emanemair/images/main/6.jpg"
img_name = img_url.split('/')[-1]
img_name

img = Image.open(BytesIO(requests.get(img_url).content))
img

img.save('original/'+img_name , format= 'jpeg')

output_path = 'masked/'+img_name
output_path

with open(output_path ,'wb')as f :
  input= open('original/'+img_name , 'rb').read()
  subject = remove(input ,alpha_matting_foreground_threshold=50)
  f.write(subject)

background_img ='https://raw.githubusercontent.com/emanemair/remove-background-/main/background.jpg'
background_img = Image.open(BytesIO(requests.get(background_img).content))

background_img = background_img.resize((img.width , img.height))

forground_img = Image.open(output_path)
background_img.paste(forground_img ,(0,0) , forground_img)
background_img.save('masked/background.jpg' , format = 'jpeg')
background_img